name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:
    
jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/site:latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with:          
          dotnet-version: 7.0.202         

      - name: Autenticação no Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}                      
      
      - name: Inserindo credenciais
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{secrets.GCP_CREDENTIALS}}
          project_id: ${{secrets.GCP_PROJECT_ID}}  

      - name: Autenticação/Construção/Push Google Cloud
        env:
          GOOGLE_PROJECT: ${{secrets.GCP_PROJECT_ID}}
        run: |
          gcloud auth configure-docker southamerica-east1-docker.pkg.dev
          docker build -t southamerica-east1-docker.pkg.dev/$GOOGLE_PROJECT/divicheck-api/divicheck-homol:latest -f CTRLInvesting.Client/Dockerfile .
          docker push southamerica-east1-docker.pkg.dev/$GOOGLE_PROJECT/divicheck-api/divicheck-homol:latest      
      
