name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:
    
jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GOOGLE_PROJECT }}/site:latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with:          
          dotnet-version: 7.0.202         

      - name: Autenticação no Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}                      
      
      - name: Inserindo credenciais
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
          project_id: ${{secrets.GOOGLE_PROJECT}}  

      - name: Autenticação Google Cloud        
        run:  |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME -f CTRLInvesting.Client/Dockerfile .

      # push image to registry
      - name: Push Docker image
        run: docker push $IMAGE_NAME

      # deploy image
      - name: Deploy Docker image
        run: gcloud run deploy site --image $IMAGE_NAME --region us-central1 --memory 128Mi --min-instances 0 --max-instances 1 --platform managed --port 80 --allow-unauthenticated
