name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:
    
jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/site:latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with:          
          dotnet-version: 7.0.202         

      - name: Autenticação no Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Construindo imagem Docker do Client
        uses: docker/build-push-action@v5.2.0
        with:
          context: .
          file: CTRLInvesting.Client/Dockerfile
          push: true
          tags: |
            604210/divicheck-client:${{github.run_number}}
            604210/divicheck-client:latest

      - name: Replace connection string
        run: |
            sed -i "s|\"ConnectionStrings:Default\":.*|\"ConnectionStrings:Default\": \"${{ secrets.DATABASE_CONNECTION_STRING }}\"|" ./CTRLInvesting.Api/appsettings.json
            
      - name: Construindo imagem Docker da Api
        uses: docker/build-push-action@v5.2.0
        with:
          context: .
          file: CTRLInvesting.Api/Dockerfile
          push: true
          tags: |
            604210/divicheck-api:${{github.run_number}}
            604210/divicheck-api:latest
      
      - name: Inserindo credenciais
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{secrets.GCP_CREDENTIALS}}
          project_id: ${{secrets.GCP_PROJECT_ID}}  

      - name: Autenticação/Construção/Push Google Cloud - API
        env:
          GOOGLE_PROJECT: ${{secrets.GCP_PROJECT_ID}}
        run: |        
          gcloud auth configure-docker southamerica-east1-docker.pkg.dev
          docker build -t southamerica-east1-docker.pkg.dev/$GOOGLE_PROJECT/divicheck-api/divicheck-homol:latest -f CTRLInvesting.Api/Dockerfile .
          docker push southamerica-east1-docker.pkg.dev/$GOOGLE_PROJECT/divicheck-api/divicheck-homol:latest
          
      - name: Autenticação/Construção/Push Google Cloud - Client
        env:
          GOOGLE_PROJECT: ${{secrets.GCP_PROJECT_ID}}
        run: |
          gcloud auth configure-docker us-east1-docker.pkg.dev
          docker build -t us-east1-docker.pkg.dev/$GOOGLE_PROJECT/divicheck-client-usa/divicheck-homol:latest -f CTRLInvesting.Client/Dockerfile .
          docker push us-east1-docker.pkg.dev/$GOOGLE_PROJECT/divicheck-client-usa/divicheck-homol:latest
          
      - name: Deploy Docker image
        env:
          GOOGLE_PROJECT: ${{secrets.GCP_PROJECT_ID}}
        run: |
          gcloud run deploy api --image southamerica-east1-docker.pkg.dev/$GOOGLE_PROJECT/divicheck-api/divicheck-homol:latest --region southamerica-east1 --platform managed --memory 256Mi --port 80 --allow-unauthenticated
          gcloud run deploy client --image us-east1-docker.pkg.dev/$GOOGLE_PROJECT/divicheck-client-usa/divicheck-homol:latest --region us-east1 --platform managed --memory 256Mi --port 80 --allow-unauthenticated
