name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:
    
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with:          
          dotnet-version: 7.0.202         

      - name: Autenticação no Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
          
          
      - name: Construindo imagem Docker do Client
        uses: docker/build-push-action@v5.2.0
        with:
          context: .
          file: CTRLInvesting.Client/Dockerfile
          push: true
          tags: |
            604210/divicheck-client:${{github.run_number}}
            604210/divicheck-client:latest     
