name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:
    
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with:          
          dotnet-version: 7.0.202         

      - name: Autenticação no Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
          
          
      - name: Construindo imagem Docker do Client
        uses: docker/build-push-action@v5.2.0
        with:
          context: .
          file: CTRLInvesting.Client/Dockerfile
          push: true
          tags: |
            604210/divicheck-client:${{github.run_number}}
            604210/divicheck-client:latest
            
      - name: Construindo imagem Docker da Api
        uses: docker/build-push-action@v5.2.0
        with:
          context: .
          file: CTRLInvesting.Api/Dockerfile
          push: true
          tags: |
            604210/divicheck-api:${{github.run_number}}
            604210/divicheck-api:latest
      
      - name: Instalando google cli
        uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          project_id: ${{secrets.GOOGLE_PROJECT}}
          service_account_key: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
          export_default_credentials: true
          
      - name: Construindo e enviando imagem docker
        env:
          GOOGLE_PROJECT: ${{secrets.GOOGLE_PROJECT}}
        run:
          gcloud auth configure-docker southamerica-east1southamerica-east1-docker.pkg.dev
          docker build -t southamerica-east1-docker.pkg.dev/$GOOGLE_PROJECT/docker/client:latest .
          docker push southamerica-east1-docker.pkg.dev/$GOOGLE_PROJECT/docker/client:latest


          
